/**
 * Bilingual translation system for Boss Control Panel
 * Supports: en (English), zh (Chinese)
 */

const LANG = {
  en: {
    /* ─── Header ─── */
    'app.title': 'Boss Control',
    'app.logout': 'Logout',
    'app.langToggle': '中',

    /* ─── Tabs ─── */
    'tab.overview': 'Overview',
    'tab.users': 'Users',
    'tab.ledger': 'Ledger',
    'tab.refund': 'Refund',
    'tab.devices': 'Devices',
    'tab.system': 'System',

    /* ─── Overview Tab ─── */
    'ov.cashToday': 'Cash Today',
    'ov.cardToday': 'Card Today',
    'ov.vatCollected': 'VAT Collected',
    'ov.netSales': 'Net Sales',
    'ov.salesCount': 'Sales Count',
    'ov.refunds': 'Refunds',
    'ov.ledgerIn': 'Ledger in',
    'ov.gross': 'Gross',
    'ov.refundLabel': '{count} refunds (-€{amount})',
    'ov.closed': 'Closed',
    'ov.noClose': 'No close yet',
    'ov.devicePL': 'Device Profit / Loss',
    'ov.soldDevices': 'Sold Devices',
    'ov.grossProfit': 'Gross Profit',
    'ov.quickActions': 'Quick Actions',
    'ov.refresh': 'Refresh',
    'ov.failedLoad': 'Failed to load overview',
    'ov.refreshed': 'Refreshed',

    /* ─── Navigation ─── */
    'nav.posTill': '🛒 POS / Till',
    'nav.inventory': '📦 Inventory',
    'nav.refunds': '💰 Refunds',
    'nav.reports': '📊 Reports',
    'nav.websiteAdmin': '🌐 Website Admin',

    /* ─── Users Tab ─── */
    'users.title': 'User Management',
    'users.create': '+ Create User',
    'users.disabled': 'disabled',
    'users.role': 'Role',
    'users.disable': 'Disable',
    'users.enable': 'Enable',
    'users.created': 'User created',
    'users.enabledMsg': 'User enabled',
    'users.disabledMsg': 'User disabled',
    'users.allFieldsReq': 'All fields required',
    'users.disableTitle': 'Disable User',
    'users.disableBody': 'This user will lose access to the system.',
    'users.notFound': 'User not found',
    'users.resetPw': 'Reset PW',
    'users.resetPwTitle': 'Reset Password',
    'users.newPassword': 'New Password',
    'users.confirmPassword': 'Confirm Password',
    'users.pwMismatch': 'Passwords do not match',
    'users.pwTooShort': 'Password must be at least 8 characters',
    'users.pwWeak': 'Password must contain at least one letter and one digit',
    'users.pwResetDone': 'Password reset successful',
    'users.edit': 'Edit',
    'users.editTitle': 'Edit User',
    'users.save': 'Save',
    'users.updated': 'User updated',
    'users.permissions': 'Permissions',
    'users.permLocked': 'Permissions are set automatically for {role} role',
    'users.delete': 'Delete User',
    'users.deleteTitle': 'Delete User',
    'users.deleteBody': 'Permanently delete <strong>{name}</strong>?',
    'users.deleteWarn': 'This cannot be undone. The user will be permanently removed.',
    'users.deleted': 'User deleted',

    /* ─── Permission Labels ─── */
    'perm.pos': 'POS / Checkout',
    'perm.products': 'Products',
    'perm.stock': 'Stock',
    'perm.suppliers': 'Suppliers',
    'perm.purchases': 'Purchases',
    'perm.transactions': 'Transactions',
    'perm.reports': 'Reports',
    'perm.invoices': 'Invoices',
    'perm.settings': 'Settings',
    'perm.users': 'Users',
    'perm.expenses': 'Expenses',
    'perm.refund': 'Refund',
    'perm.website': 'Website',

    /* ─── Create User Modal ─── */
    'cu.title': 'Create User',
    'cu.username': 'Username',
    'cu.password': 'Password',
    'cu.passwordPlaceholder': 'Min 8 characters, letter + digit',
    'cu.displayName': 'Display Name',
    'cu.displayPlaceholder': 'Display name',
    'cu.role': 'Role',
    'cu.staff': 'Staff',
    'cu.manager': 'Manager',
    'cu.root': 'Root',
    'cu.create': 'Create',

    /* ─── Ledger Tab ─── */
    'ledger.title': 'Cash Ledger',
    'ledger.all': 'All',
    'ledger.sales': 'Sales',
    'ledger.refunds': 'Refunds',
    'ledger.expenses': 'Expenses',
    'ledger.netFlow': 'Net Flow',
    'ledger.noEntries': 'No entries',
    'ledger.showing': 'Showing {count} of {total} entries',

    /* ─── Entry Types ─── */
    'entry.sale': 'Sale',
    'entry.refund': 'Refund',
    'entry.expense': 'Expense',
    'entry.supplier': 'Supplier',
    'entry.device_buy': 'Device Buy',
    'entry.bank_in': 'Bank In',
    'entry.bank_out': 'Bank Out',

    /* ─── Refund Tab ─── */
    'refund.forceTitle': 'Force Refund',
    'refund.receipt': 'Receipt Number',
    'refund.receiptPlaceholder': 'e.g. S-20260507-001',
    'refund.method': 'Refund Method',
    'refund.cash': 'Cash',
    'refund.card': 'Card',
    'refund.reason': 'Reason',
    'refund.reasonPlaceholder': 'Root forced refund',
    'refund.execute': 'Execute Refund',
    'refund.reverseTitle': 'Reverse Refund',
    'refund.reverseReceipt': 'Refund Receipt Number',
    'refund.reverseReceiptPlaceholder': 'e.g. R-20260507-001',
    'refund.reverseBtn': 'Reverse Refund',
    'refund.recent': 'Recent Refunds',
    'refund.noRefunds': 'No refunds',
    'refund.original': 'Original',
    'refund.receiptReq': 'Receipt number required',
    'refund.reverseReceiptReq': 'Refund receipt number required',
    'refund.executed': 'Refund executed: €{amount}',
    'refund.reversed': 'Refund reversed',
    'refund.confirmExecute': 'Refund <strong>{receipt}</strong> via <strong>{method}</strong>?',
    'refund.confirmExecuteWarn': 'This will reverse the full transaction amount.',
    'refund.confirmReverse': 'Reverse refund <strong>{receipt}</strong>?',
    'refund.confirmReverseWarn': 'This will create a compensating refund to reverse the original refund.',

    /* ─── Devices Tab ─── */
    'devices.title': 'Device Inventory',
    'devices.all': 'All',
    'devices.sold': 'Sold',
    'devices.tested': 'Tested',
    'devices.pending': 'Pending',
    'devices.buyIn': 'Buy In',
    'devices.total': 'Total Devices',
    'devices.totalBuy': 'Total Buy',
    'devices.totalSell': 'Total Sell',
    'devices.grossProfit': 'Gross Profit',
    'devices.noDevices': 'No devices',
    'devices.buy': 'Buy',
    'devices.sell': 'Sell',
    'devices.pl': 'PL',
    'devices.edit': 'Edit',
    'devices.showing': 'Showing {count} of {total}',
    'devices.notFound': 'Device not found',
    'devices.updated': 'Device updated',

    /* ─── Device Edit Modal ─── */
    'devEdit.title': 'Edit Device',
    'devEdit.buyPrice': 'Buy Price (€)',
    'devEdit.sellPrice': 'Sell Price (€)',
    'devEdit.status': 'Status',
    'devEdit.notes': 'Notes',
    'devEdit.save': 'Save',

    /* ─── System Tab ─── */
    'sys.status': 'System Status',
    'sys.serverTime': 'Server Time',
    'sys.activeUsers': 'Active Users',
    'sys.activeUsersVal': '{count} active',
    'sys.posStatus': 'POS Status',
    'sys.paused': 'PAUSED',
    'sys.running': 'Running',
    'sys.txnLocked': 'Transactions Locked',
    'sys.locked': 'Locked',
    'sys.unlocked': 'Unlocked',
    'sys.lastClose': 'Last Daily Close',
    'sys.noClose': 'No close yet',
    'sys.dailyClose': 'Daily Close',
    'sys.date': 'Date',
    'sys.forceClose': 'Force Close',
    'sys.reopen': 'Reopen',
    'sys.emergency': '⚠ Emergency Controls',
    'sys.pausePos': 'Pause POS',
    'sys.resumePos': 'Resume POS',
    'sys.lockTxns': 'Lock All Transactions',
    'sys.auditLog': 'Audit Log',
    'sys.loadAudit': 'Load Recent Actions',
    'sys.openAudit': 'Open Audit Dashboard',
    'sys.export': 'Export & Tax Preparation',
    'sys.startDate': 'Start Date',
    'sys.endDate': 'End Date',
    'sys.failedLoad': 'Failed to load system status',
    'sys.selectDate': 'Select a date',

    /* ─── Export ─── */
    'export.transactions': 'Transactions',
    'export.ledger': 'Ledger',
    'export.audit': 'Audit',
    'export.dailyClose': 'Daily Close',
    'export.vatSummary': 'VAT Summary',
    'export.download': 'Download {label} as CSV?',
    'export.period': 'Period: {start} → {end}',
    'export.notAuth': 'Not authenticated',
    'export.downloading': 'Downloading {label}…',
    'export.downloaded': '{label} downloaded',
    'export.failed': 'Export failed',

    /* ─── Daily Close Confirm Modals ─── */
    'close.forceTitle': 'Force Daily Close',
    'close.forceBody': 'Close <strong>{date}</strong>?',
    'close.forceWarn': 'This will lock all transactions for this day.',
    'close.forceDone': 'Daily close completed for {date}',
    'close.reopenTitle': 'Reopen Daily Close',
    'close.reopenBody': 'Reopen <strong>{date}</strong>?',
    'close.reopenWarn': 'This will allow modifications to closed day transactions. Use with caution.',
    'close.reopenDone': 'Daily close reopened for {date}',

    /* ─── System Control Modals ─── */
    'ctrl.pauseTitle': 'Pause POS System',
    'ctrl.pauseBody': 'This will STOP all POS operations immediately.',
    'ctrl.pauseWarn': 'Staff will not be able to process sales.',
    'ctrl.pauseBtn': 'Pause System',
    'ctrl.pauseDone': 'System paused',
    'ctrl.resumeTitle': 'Resume POS System',
    'ctrl.resumeBody': 'Restore normal POS operations?',
    'ctrl.resumeBtn': 'Resume',
    'ctrl.resumeDone': 'System resumed',
    'ctrl.lockTitle': 'Lock All Transactions',
    'ctrl.lockWarn': 'This will prevent ANY modification to historical transactions.',
    'ctrl.lockSub': 'This action is reversible via system controls.',
    'ctrl.lockBtn': 'Lock All',
    'ctrl.lockDone': 'Transactions locked',

    /* ─── Confirm Modal ─── */
    'modal.confirm': 'Confirm',
    'modal.cancel': 'Cancel',

    /* ─── Audit Page ─── */
    'audit.title': 'Audit Log',
    'audit.back': '← Back',
    'audit.filters': 'Filters',
    'audit.startDate': 'Start Date',
    'audit.endDate': 'End Date',
    'audit.actionType': 'Action Type',
    'audit.allActions': 'All Actions',
    'audit.systemLock': 'System Lock',
    'audit.systemUnlock': 'System Unlock',
    'audit.systemPause': 'System Pause',
    'audit.systemResume': 'System Resume',
    'audit.lockTxns': 'Lock Transactions',
    'audit.forceRefund': 'Force Refund',
    'audit.reverseRefund': 'Reverse Refund',
    'audit.forceClose': 'Force Close',
    'audit.reopenClose': 'Reopen Close',
    'audit.userCreate': 'User Create',
    'audit.userUpdate': 'User Update',
    'audit.userDelete': 'User Delete',
    'audit.userDisable': 'User Disable',
    'audit.deviceUpdate': 'Device Update',
    'audit.moduleAll': 'All',
    'audit.moduleSystem': 'System',
    'audit.moduleRefund': 'Refund',
    'audit.moduleDailyClose': 'Daily Close',
    'audit.moduleUser': 'User',
    'audit.moduleDevice': 'Device',
    'audit.search': 'Search',
    'audit.entries': 'Audit Entries',
    'audit.entryCount': '{count} entries',
    'audit.loadMore': 'Load More',
    'audit.loading': 'Loading...',
    'audit.noEntries': 'No audit entries found',
    'audit.before': 'Before',
    'audit.after': 'After',
    'audit.none': 'none',

    /* ─── Errors / Toasts ─── */
    'err.sessionExpired': 'Session expired. Please login again.',
    'err.authFailed': 'Auth failed',
    'err.noToken': 'No token',
    'err.requestFailed': 'Request failed',
    'err.network': 'Network error',

    /* ─── SaaS Platform ─── */
    'saas.login.title': 'Store Owner Login',
    'saas.login.subtitle': 'Sign in to manage your store',
    'saas.login.username': 'Username',
    'saas.login.password': 'Password',
    'saas.login.usernamePlaceholder': 'Enter your username',
    'saas.login.passwordPlaceholder': 'Enter your password',
    'saas.login.btn': 'Sign In',
    'saas.login.signingIn': 'Signing in...',
    'saas.login.error.fields': 'Username and password required',
    'saas.login.error.invalid': 'Invalid credentials',
    'saas.login.error.network': 'Network error',
    'saas.login.noAccount': "Don't have a store?",
    'saas.login.createOne': 'Create one',
    'saas.login.backHome': '← Back to homepage',

    'saas.register.title': 'Create Your Store',
    'saas.register.subtitle': "Fill in the details below. We'll review and activate your account.",
    'saas.register.storeName': 'Store Name *',
    'saas.register.storeNamePlaceholder': 'e.g. Navan Repairs',
    'saas.register.businessType': 'Business Type',
    'saas.register.businessTypePlaceholder': 'Select...',
    'saas.register.phoneRepair': 'Phone Repair',
    'saas.register.computerRepair': 'Computer Repair',
    'saas.register.electronicsRetail': 'Electronics Retail',
    'saas.register.phoneAccessories': 'Phone Accessories',
    'saas.register.other': 'Other',
    'saas.register.ownerName': 'Owner Name *',
    'saas.register.ownerNamePlaceholder': 'Your full name',
    'saas.register.email': 'Email *',
    'saas.register.emailPlaceholder': 'your@email.com',
    'saas.register.phone': 'Phone',
    'saas.register.phonePlaceholder': '+353 8X XXX XXXX',
    'saas.register.country': 'Country',
    'saas.register.countryPlaceholder': 'e.g. Ireland',
    'saas.register.notes': 'Notes / Special Requirements',
    'saas.register.notesPlaceholder': 'Tell us about your business...',
    'saas.register.btn': 'Submit Registration',
    'saas.register.submitting': 'Submitting...',
    'saas.register.success.title': '✅ Registration Submitted!',
    'saas.register.success.body': "Thank you for your interest in TechCross SaaS.<br><br>We'll review your application and get back to you at <strong id=\"successEmail\"></strong>.<br><br>In the meantime, feel free to <a href=\"/saas\" style=\"color:#0071e3;\">learn more</a> about the platform.",
    'saas.register.error.fields': 'Please fill in required fields',
    'saas.register.error.duplicate': 'A pending signup already exists for this email',
    'saas.register.error.network': 'Network error. Please try again.',
    'saas.register.backHome': '← Back to homepage',

    'saas.admin.title': 'Super Admin Console',
    'saas.admin.tab.stores': 'Stores',
    'saas.admin.tab.signups': 'Signups',
    'saas.admin.allStores': 'All Stores',
    'saas.admin.pendingSignups': 'Pending Signups',
    'saas.admin.btn.enter': 'Enter Store',
    'saas.admin.btn.users': 'Users',
    'saas.admin.btn.suspend': 'Suspend',
    'saas.admin.btn.activate': 'Activate',
    'saas.admin.btn.approve': 'Approve',
    'saas.admin.btn.reject': 'Reject',
    'saas.admin.btn.delete': 'Delete',
    'saas.admin.btn.disable': 'Disable',
    'saas.admin.btn.enable': 'Enable',
    'saas.admin.users.title': 'Users — {name}',
    'saas.admin.users.colUsername': 'Username',
    'saas.admin.users.colName': 'Name',
    'saas.admin.users.colRole': 'Role',
    'saas.admin.users.colStatus': 'Status',
    'saas.admin.status.active': 'active',
    'saas.admin.status.disabled': 'disabled',
    'saas.admin.loading': 'Loading...',
    'saas.admin.empty.stores': 'No stores yet.',
    'saas.admin.empty.signups': 'No pending signups.',
    'saas.admin.empty.users': 'No users for this store.',
    'saas.admin.toast.approved': 'Store {name} approved!',
    'saas.admin.toast.rejected': 'Signup rejected',
    'saas.admin.toast.suspended': 'Store suspended',
    'saas.admin.toast.activated': 'Store activated',
    'saas.admin.toast.entered': 'Entered {name}. Token updated.',
    'saas.admin.toast.userDeleted': 'User deleted',
    'saas.admin.toast.userDisabled': 'User disabled',
    'saas.admin.toast.userEnabled': 'User enabled',
    'saas.admin.toast.failed': 'Failed: {error}',
    'saas.admin.signOut': 'Sign Out',
    'saas.admin.colActions': 'Actions',
    'saas.admin.signups.colStore': 'Store',
    'saas.admin.signups.colOwner': 'Owner',
    'saas.admin.signups.colEmail': 'Email',
    'saas.admin.signups.colType': 'Type',
    'saas.admin.signups.colDate': 'Date',
    'saas.admin.status.suspended': 'suspended',
    'saas.admin.status.pending': 'pending',
    'saas.admin.confirm.suspend': 'Suspend this store?',
    'saas.admin.confirm.approve': 'Approve this signup? A store account will be created.',
    'saas.admin.confirm.reject': 'Reject this signup?',
    'saas.admin.confirm.deleteUser': 'Delete this user? This cannot be undone.',
    'saas.admin.confirm.disableUser': 'Disable this user?',
    'saas.admin.toast.unknownError': 'unknown error',
    'saas.admin.toast.approvalFailed': 'Approval failed',
    'saas.admin.toast.deleteFailed': 'Delete failed',
    'saas.admin.toast.failedGeneric': 'Failed',
    'saas.admin.toast.approvedWithUser': 'Store {name} approved! Username: {username}',
    'saas.admin.btn.edit': 'Edit',
    'saas.admin.btn.resetPw': 'Reset Password',
    'saas.admin.btn.emailPw': 'Email Password',
    'saas.admin.editUser.title': 'Edit User',
    'saas.admin.editUser.username': 'Username',
    'saas.admin.editUser.displayName': 'Display Name',
    'saas.admin.editUser.email': 'Email',
    'saas.admin.editUser.password': 'New Password (leave blank to keep current)',
    'saas.admin.editUser.cancel': 'Cancel',
    'saas.admin.editUser.save': 'Save',
    'saas.admin.editUser.saving': 'Saving...',
    'saas.admin.toast.userUpdated': 'User updated',
    'saas.admin.confirm.resetPw': 'Reset password for this user? A new password will be generated.',
    'saas.admin.confirm.emailPw': 'Reset password and email credentials to the user?',
    'saas.admin.toast.passwordReset': 'Password reset',
    'saas.admin.toast.emailPwSent': 'Credentials emailed successfully',
    'saas.admin.emailPwWarning': 'Password reset but email failed:\n{warning}',
    'saas.admin.resetPwResult': 'Password reset for {username}\nNew password: {password}\n\nPlease share this securely with the user.',
    'saas.admin.btn.deleteStore': 'Delete',
    'saas.admin.delete.title': 'Delete Store',
    'saas.admin.delete.confirm': 'Enter the current Dublin time (HHMM) as secondary password. All store data and users will be removed.',
    'saas.admin.delete.hint': 'Current Dublin time:',
    'saas.admin.delete.label': 'Secondary Password (HHMM)',
    'saas.admin.delete.cancel': 'Cancel',
    'saas.admin.delete.confirmBtn': 'Delete Forever',
    'saas.admin.delete.noPw': 'Please enter your password',
    'saas.admin.delete.finalWarning': 'This will permanently delete the store and all associated users. Continue?',
    'saas.admin.delete.deleting': 'Deleting...',
    'saas.admin.toast.storeDeleted': 'Store and all users deleted',

    /* ─── SaaS Dashboard Password ─── */
    'saas.dash.password.title': 'Change Password',
    'saas.dash.password.current': 'Current Password',
    'saas.dash.password.new': 'New Password',
    'saas.dash.password.confirm': 'Confirm New Password',
    'saas.dash.password.btn': 'Update Password',
    'saas.dash.password.saving': 'Updating...',
    'saas.dash.password.saved': 'Password updated successfully!',
    'saas.dash.password.errorRequired': 'Please fill in both passwords',
    'saas.dash.password.errorLength': 'New password must be at least 6 characters',
    'saas.dash.password.errorMismatch': 'Passwords do not match',
    'saas.dash.password.errorGeneric': 'Password update failed',

    /* ─── SaaS Landing ─── */
    'saas.landing.nav.features': 'Features',
    'saas.landing.nav.pricing': 'Pricing',
    'saas.landing.nav.storeLogin': 'Store Login',
    'saas.landing.nav.createStore': 'Create Your Store',
    'saas.landing.hero.title': 'Run Your Repair Shop with TechCross SaaS',
    'saas.landing.hero.subtitle': 'Everything you need to manage repairs, POS, inventory, and staff — in one modern platform.',
    'saas.landing.hero.btnCreate': 'Create Your Store',
    'saas.landing.hero.btnLogin': 'Store Owner Login',
    'saas.landing.features.title': 'All-in-One Shop Management',
    'saas.landing.features.subtitle': 'Built for phone and electronics repair shops, by people who know the trade.',
    'saas.landing.features.pos': 'Point of Sale',
    'saas.landing.features.posDesc': 'Fast, intuitive POS with barcode scanning, discounts, and multi-payment support.',
    'saas.landing.features.inventory': 'Inventory',
    'saas.landing.features.inventoryDesc': 'Track stock, manage suppliers, receive purchase orders, and get low-stock alerts.',
    'saas.landing.features.repair': 'Repair Workflow',
    'saas.landing.features.repairDesc': 'Full repair lifecycle: check-in, diagnostics, parts ordering, status updates, collection.',
    'saas.landing.features.vat': 'VAT Compliance',
    'saas.landing.features.vatDesc': 'Automatic 23%/13.5% VAT, margin scheme for second-hand goods, and tax reports.',
    'saas.landing.features.receipts': 'Receipts & Invoices',
    'saas.landing.features.receiptsDesc': 'Professional receipts and VAT invoices with automatic numbering and email delivery.',
    'saas.landing.features.whatsapp': 'WhatsApp Integration',
    'saas.landing.features.whatsappDesc': 'Send repair updates, quotes, and invoices directly to customers via WhatsApp.',
    'saas.landing.features.reports': 'Reports',
    'saas.landing.features.reportsDesc': 'Daily sales, profit & loss, VAT summaries, and monthly close reports.',
    'saas.landing.features.staff': 'Multi-User Staff',
    'saas.landing.features.staffDesc': 'Role-based accounts: staff, manager, and store owner with granular permissions.',
    'saas.landing.features.printing': 'Thermal Printing',
    'saas.landing.features.printingDesc': 'ESC/POS receipt printing with local print agent — works with standard 80mm printers.',
    'saas.landing.screenshots.title': 'See It in Action',
    'saas.landing.screenshots.subtitle': 'Clean, fast, and built for the counter.',
    'saas.landing.pricing.title': 'Simple Pricing',
    'saas.landing.pricing.subtitle': 'Start small, scale as you grow. No hidden fees.',
    'saas.landing.pricing.starter': 'Starter',
    'saas.landing.pricing.perMonth': 'per month',
    'saas.landing.pricing.starter.f1': 'Up to 500 transactions/month',
    'saas.landing.pricing.starter.f2': '1 staff account',
    'saas.landing.pricing.starter.f3': 'Basic inventory',
    'saas.landing.pricing.starter.f4': 'Receipt printing',
    'saas.landing.pricing.starter.f5': 'Email support',
    'saas.landing.pricing.starterBtn': 'Get Started',
    'saas.landing.pricing.pro': 'Pro',
    'saas.landing.pricing.pro.f1': 'Unlimited transactions',
    'saas.landing.pricing.pro.f2': 'Up to 5 staff accounts',
    'saas.landing.pricing.pro.f3': 'Full inventory + suppliers',
    'saas.landing.pricing.pro.f4': 'VAT compliance & reports',
    'saas.landing.pricing.pro.f5': 'WhatsApp integration',
    'saas.landing.pricing.pro.f6': 'Priority support',
    'saas.landing.pricing.proBtn': 'Get Started',
    'saas.landing.pricing.enterprise': 'Enterprise',
    'saas.landing.pricing.enterprise.f1': 'Unlimited everything',
    'saas.landing.pricing.enterprise.f2': 'Unlimited staff accounts',
    'saas.landing.pricing.enterprise.f3': 'Multi-store support',
    'saas.landing.pricing.enterprise.f4': 'Custom integrations',
    'saas.landing.pricing.enterprise.f5': 'Dedicated account manager',
    'saas.landing.pricing.enterprise.f6': '99.9% SLA',
    'saas.landing.pricing.enterpriseBtn': 'Contact Us',
    'saas.landing.cta.title': 'Ready to Take Control?',
    'saas.landing.cta.subtitle': 'Join shop owners who trust TechCross to run their business.',
    'saas.landing.cta.btn': "Create Your Store — It's Free to Start",
    'saas.landing.footer': '© 2026 TechCross. All rights reserved.',

    'saas.dash.greeting.super': 'Super Admin Panel',
    'saas.dash.greeting.owner': 'Store Owner Dashboard',
    'saas.dash.greeting.staff': 'Staff Dashboard',
    'saas.dash.welcome': 'Welcome!',
    'saas.dash.subtitle': 'You are signed in to the SaaS platform.',
    'saas.dash.username': 'Username',
    'saas.dash.name': 'Name',
    'saas.dash.role': 'Role',
    'saas.dash.storeId': 'Store ID',
    'saas.dash.storeNone': 'N/A (super admin)',
    'saas.dash.adminBanner.title': 'Welcome, Super Admin',
    'saas.dash.adminBanner.desc': 'You have full access to all stores.',
    'saas.dash.adminBanner.btn': 'Open Admin Console',
    'saas.dash.signOut': 'Sign Out',

    /* ─── Store Settings (SaaS) ─── */
    'saas.dash.storeInfo': 'Store Information',
    'saas.dash.settings.title': 'Store Settings',
    'saas.dash.settings.logo': 'Store Logo',
    'saas.dash.settings.uploadLogo': 'Upload Logo',
    'saas.dash.settings.logoTooBig': 'Logo must be under 2MB',
    'saas.dash.settings.storeName': 'Store Name',
    'saas.dash.settings.storeNamePlaceholder': 'Your store name',
    'saas.dash.settings.address': 'Address',
    'saas.dash.settings.addressPlaceholder': 'Full store address',
    'saas.dash.settings.phone': 'Phone',
    'saas.dash.settings.phonePlaceholder': 'Phone number',
    'saas.dash.settings.email': 'Email',
    'saas.dash.settings.emailPlaceholder': 'Email address',
    'saas.dash.settings.vatNumber': 'VAT Number',
    'saas.dash.settings.vatPlaceholder': 'IE1234567X',
    'saas.dash.settings.receiptTC': 'Receipt Terms & Conditions',
    'saas.dash.settings.tcPlaceholder': 'e.g. No refund after 14 days, warranty terms...',
    'saas.dash.settings.save': 'Save Settings',
    'saas.dash.settings.saving': 'Saving...',
    'saas.dash.settings.saved': 'Settings saved!',
    'saas.dash.settings.reset': 'Reset',
  },

  zh: {
    /* ─── Header ─── */
    'app.title': '老板控制面板',
    'app.logout': '退出登录',
    'app.langToggle': 'EN',

    /* ─── Tabs ─── */
    'tab.overview': '总览',
    'tab.users': '用户',
    'tab.ledger': '流水',
    'tab.refund': '退款',
    'tab.devices': '设备',
    'tab.system': '系统',

    /* ─── Overview Tab ─── */
    'ov.cashToday': '今日现金',
    'ov.cardToday': '今日刷卡',
    'ov.vatCollected': 'VAT 总额',
    'ov.netSales': '净销售额',
    'ov.salesCount': '销售笔数',
    'ov.refunds': '退款总额',
    'ov.ledgerIn': '账本收入',
    'ov.gross': '毛销售额',
    'ov.refundLabel': '{count} 笔退款 (-€{amount})',
    'ov.closed': '已日结',
    'ov.noClose': '未日结',
    'ov.devicePL': '设备损益',
    'ov.soldDevices': '已售设备',
    'ov.grossProfit': '毛利润',
    'ov.quickActions': '快捷操作',
    'ov.refresh': '刷新',
    'ov.failedLoad': '加载总览失败',
    'ov.refreshed': '已刷新',

    /* ─── Navigation ─── */
    'nav.posTill': '🛒 POS / 收银',
    'nav.inventory': '📦 库存管理',
    'nav.refunds': '💰 退款',
    'nav.reports': '📊 报表',
    'nav.websiteAdmin': '🌐 网站管理',

    /* ─── Users Tab ─── */
    'users.title': '用户管理',
    'users.create': '+ 创建用户',
    'users.disabled': '已停用',
    'users.role': '角色',
    'users.disable': '停用',
    'users.enable': '启用',
    'users.created': '用户已创建',
    'users.enabledMsg': '用户已启用',
    'users.disabledMsg': '用户已停用',
    'users.allFieldsReq': '请填写所有字段',
    'users.disableTitle': '停用用户',
    'users.disableBody': '该用户将无法登录系统。',
    'users.notFound': '用户未找到',
    'users.resetPw': '重置密码',
    'users.resetPwTitle': '重置密码',
    'users.newPassword': '新密码',
    'users.confirmPassword': '确认密码',
    'users.pwMismatch': '两次密码不一致',
    'users.pwTooShort': '密码至少8个字符',
    'users.pwWeak': '密码必须包含至少一个字母和一个数字',
    'users.pwResetDone': '密码重置成功',
    'users.edit': '编辑',
    'users.editTitle': '编辑用户',
    'users.save': '保存',
    'users.updated': '用户已更新',
    'users.permissions': '权限设置',
    'users.permLocked': '{role} 角色的权限为自动设置',
    'users.delete': '删除用户',
    'users.deleteTitle': '删除用户',
    'users.deleteBody': '永久删除 <strong>{name}</strong>？',
    'users.deleteWarn': '此操作不可撤销，用户将被永久移除。',
    'users.deleted': '用户已删除',

    /* ─── Permission Labels ─── */
    'perm.pos': 'POS / 收银',
    'perm.products': '商品管理',
    'perm.stock': '库存管理',
    'perm.suppliers': '供应商管理',
    'perm.purchases': '采购管理',
    'perm.transactions': '交易记录',
    'perm.reports': '报表中心',
    'perm.invoices': '发票管理',
    'perm.settings': '系统设置',
    'perm.users': '用户管理',
    'perm.expenses': '每日支出',
    'perm.refund': '退款',
    'perm.website': '网站管理',

    /* ─── Create User Modal ─── */
    'cu.title': '创建用户',
    'cu.username': '用户名',
    'cu.password': '密码',
    'cu.passwordPlaceholder': '至少 8 位，需包含字母和数字',
    'cu.displayName': '显示名称',
    'cu.displayPlaceholder': '显示名称',
    'cu.role': '角色',
    'cu.staff': '员工',
    'cu.manager': '经理',
    'cu.root': '老板',
    'cu.create': '创建',

    /* ─── Ledger Tab ─── */
    'ledger.title': '现金流水账',
    'ledger.all': '全部',
    'ledger.sales': '销售',
    'ledger.refunds': '退款',
    'ledger.expenses': '支出',
    'ledger.netFlow': '净流量',
    'ledger.noEntries': '无记录',
    'ledger.showing': '显示 {count} / {total} 条',

    /* ─── Entry Types ─── */
    'entry.sale': '销售',
    'entry.refund': '退款',
    'entry.expense': '支出',
    'entry.supplier': '供应商',
    'entry.device_buy': '设备购入',
    'entry.bank_in': '银行入账',
    'entry.bank_out': '银行出账',

    /* ─── Refund Tab ─── */
    'refund.forceTitle': '强制退款',
    'refund.receipt': '收据编号',
    'refund.receiptPlaceholder': '例如 S-20260507-001',
    'refund.method': '退款方式',
    'refund.cash': '现金',
    'refund.card': '刷卡',
    'refund.reason': '原因',
    'refund.reasonPlaceholder': '老板强制退款',
    'refund.execute': '执行退款',
    'refund.reverseTitle': '撤销退款',
    'refund.reverseReceipt': '退款收据编号',
    'refund.reverseReceiptPlaceholder': '例如 R-20260507-001',
    'refund.reverseBtn': '撤销退款',
    'refund.recent': '最近退款',
    'refund.noRefunds': '无退款记录',
    'refund.original': '原始单据',
    'refund.receiptReq': '请输入收据编号',
    'refund.reverseReceiptReq': '请输入退款收据编号',
    'refund.executed': '退款已执行：€{amount}',
    'refund.reversed': '退款已撤销',
    'refund.confirmExecute': '退款 <strong>{receipt}</strong>，方式 <strong>{method}</strong>？',
    'refund.confirmExecuteWarn': '这将撤销该笔交易的完整金额。',
    'refund.confirmReverse': '撤销退款 <strong>{receipt}</strong>？',
    'refund.confirmReverseWarn': '这将创建一笔冲销交易来撤销原退款。',

    /* ─── Devices Tab ─── */
    'devices.title': '设备库存',
    'devices.all': '全部',
    'devices.sold': '已售',
    'devices.tested': '已测试',
    'devices.pending': '待处理',
    'devices.buyIn': '已购入',
    'devices.total': '设备总数',
    'devices.totalBuy': '购入总额',
    'devices.totalSell': '出售总额',
    'devices.grossProfit': '毛利润',
    'devices.noDevices': '无设备',
    'devices.buy': '购入价',
    'devices.sell': '售价',
    'devices.pl': '损益',
    'devices.edit': '编辑',
    'devices.showing': '显示 {count} / {total}',
    'devices.notFound': '设备未找到',
    'devices.updated': '设备已更新',

    /* ─── Device Edit Modal ─── */
    'devEdit.title': '编辑设备',
    'devEdit.buyPrice': '购入价 (€)',
    'devEdit.sellPrice': '售价 (€)',
    'devEdit.status': '状态',
    'devEdit.notes': '备注',
    'devEdit.save': '保存',

    /* ─── System Tab ─── */
    'sys.status': '系统状态',
    'sys.serverTime': '服务器时间',
    'sys.activeUsers': '活跃用户',
    'sys.activeUsersVal': '{count} 个在线',
    'sys.posStatus': 'POS 状态',
    'sys.paused': '已暂停',
    'sys.running': '运行中',
    'sys.txnLocked': '交易锁定',
    'sys.locked': '已锁定',
    'sys.unlocked': '未锁定',
    'sys.lastClose': '最近日结',
    'sys.noClose': '未日结',
    'sys.dailyClose': '日结操作',
    'sys.date': '日期',
    'sys.forceClose': '强制日结',
    'sys.reopen': '重新开启',
    'sys.emergency': '⚠ 紧急控制',
    'sys.pausePos': '暂停 POS',
    'sys.resumePos': '恢复 POS',
    'sys.lockTxns': '锁定所有交易',
    'sys.auditLog': '审计日志',
    'sys.loadAudit': '加载最近操作',
    'sys.openAudit': '打开审计面板',
    'sys.export': '导出与税务准备',
    'sys.startDate': '开始日期',
    'sys.endDate': '结束日期',
    'sys.failedLoad': '加载系统状态失败',
    'sys.selectDate': '请选择日期',

    /* ─── Export ─── */
    'export.transactions': '交易记录',
    'export.ledger': '流水账',
    'export.audit': '审计日志',
    'export.dailyClose': '日结报告',
    'export.vatSummary': 'VAT 汇总',
    'export.download': '下载 {label} CSV？',
    'export.period': '期间：{start} → {end}',
    'export.notAuth': '未登录',
    'export.downloading': '正在下载 {label}…',
    'export.downloaded': '{label} 已下载',
    'export.failed': '导出失败',

    /* ─── Daily Close Confirm Modals ─── */
    'close.forceTitle': '强制日结',
    'close.forceBody': '日结 <strong>{date}</strong>？',
    'close.forceWarn': '这将锁定当天的所有交易。',
    'close.forceDone': '{date} 日结已完成',
    'close.reopenTitle': '重新开启日结',
    'close.reopenBody': '重新开启 <strong>{date}</strong>？',
    'close.reopenWarn': '这将允许修改已日结的交易，请谨慎操作。',
    'close.reopenDone': '{date} 日结已重新开启',

    /* ─── System Control Modals ─── */
    'ctrl.pauseTitle': '暂停 POS 系统',
    'ctrl.pauseBody': '这将立即停止所有 POS 操作。',
    'ctrl.pauseWarn': '员工将无法进行销售。',
    'ctrl.pauseBtn': '暂停系统',
    'ctrl.pauseDone': '系统已暂停',
    'ctrl.resumeTitle': '恢复 POS 系统',
    'ctrl.resumeBody': '恢复正常的 POS 操作？',
    'ctrl.resumeBtn': '恢复',
    'ctrl.resumeDone': '系统已恢复',
    'ctrl.lockTitle': '锁定所有交易',
    'ctrl.lockWarn': '这将禁止修改任何历史交易。',
    'ctrl.lockSub': '此操作可通过系统控制撤销。',
    'ctrl.lockBtn': '全部锁定',
    'ctrl.lockDone': '交易已锁定',

    /* ─── Confirm Modal ─── */
    'modal.confirm': '确认',
    'modal.cancel': '取消',

    /* ─── Audit Page ─── */
    'audit.title': '审计日志',
    'audit.back': '← 返回',
    'audit.filters': '筛选条件',
    'audit.startDate': '开始日期',
    'audit.endDate': '结束日期',
    'audit.actionType': '操作类型',
    'audit.allActions': '全部操作',
    'audit.systemLock': '系统锁定',
    'audit.systemUnlock': '系统解锁',
    'audit.systemPause': '系统暂停',
    'audit.systemResume': '系统恢复',
    'audit.lockTxns': '锁定交易',
    'audit.forceRefund': '强制退款',
    'audit.reverseRefund': '撤销退款',
    'audit.forceClose': '强制日结',
    'audit.reopenClose': '重新日结',
    'audit.userCreate': '创建用户',
    'audit.userUpdate': '更新用户',
    'audit.userDelete': '删除用户',
    'audit.userDisable': '停用用户',
    'audit.deviceUpdate': '更新设备',
    'audit.moduleAll': '全部',
    'audit.moduleSystem': '系统',
    'audit.moduleRefund': '退款',
    'audit.moduleDailyClose': '日结',
    'audit.moduleUser': '用户',
    'audit.moduleDevice': '设备',
    'audit.search': '搜索',
    'audit.entries': '审计记录',
    'audit.entryCount': '{count} 条记录',
    'audit.loadMore': '加载更多',
    'audit.loading': '加载中…',
    'audit.noEntries': '未找到审计记录',
    'audit.before': '之前',
    'audit.after': '之后',
    'audit.none': '无',

    /* ─── Errors / Toasts ─── */
    'err.sessionExpired': '会话已过期，请重新登录。',
    'err.authFailed': '认证失败',
    'err.noToken': '无令牌',
    'err.requestFailed': '请求失败',
    'err.network': '网络错误',

    /* ─── SaaS Platform ─── */
    'saas.login.title': '店主登录',
    'saas.login.subtitle': '登录管理您的店铺',
    'saas.login.username': '用户名',
    'saas.login.password': '密码',
    'saas.login.usernamePlaceholder': '请输入用户名',
    'saas.login.passwordPlaceholder': '请输入密码',
    'saas.login.btn': '登录',
    'saas.login.signingIn': '正在登录…',
    'saas.login.error.fields': '请输入用户名和密码',
    'saas.login.error.invalid': '用户名或密码错误',
    'saas.login.error.network': '网络错误',
    'saas.login.noAccount': '还没有店铺？',
    'saas.login.createOne': '立即注册',
    'saas.login.backHome': '← 返回首页',

    'saas.register.title': '创建店铺',
    'saas.register.subtitle': '填写以下信息，我们将审核并激活您的账户。',
    'saas.register.storeName': '店铺名称 *',
    'saas.register.storeNamePlaceholder': '例如：天河维修中心',
    'saas.register.businessType': '业务类型',
    'saas.register.businessTypePlaceholder': '请选择…',
    'saas.register.phoneRepair': '手机维修',
    'saas.register.computerRepair': '电脑维修',
    'saas.register.electronicsRetail': '电子产品零售',
    'saas.register.phoneAccessories': '手机配件',
    'saas.register.other': '其他',
    'saas.register.ownerName': '店主姓名 *',
    'saas.register.ownerNamePlaceholder': '请输入您的姓名',
    'saas.register.email': '邮箱 *',
    'saas.register.emailPlaceholder': 'your@email.com',
    'saas.register.phone': '电话',
    'saas.register.phonePlaceholder': '+86 138 XXXX XXXX',
    'saas.register.country': '国家',
    'saas.register.countryPlaceholder': '例如：中国',
    'saas.register.notes': '备注 / 特殊需求',
    'saas.register.notesPlaceholder': '请描述您的业务和特殊需求…',
    'saas.register.btn': '提交注册',
    'saas.register.submitting': '正在提交…',
    'saas.register.success.title': '✅ 注册已提交！',
    'saas.register.success.body': '感谢您对 TechCross SaaS 的关注。<br><br>我们会审核您的申请并通过 <strong id="successEmail"></strong> 与您联系。<br><br>在此期间，您可以<a href="/saas" style="color:#0071e3;">了解更多</a>关于平台的信息。',
    'saas.register.error.fields': '请填写必填字段',
    'saas.register.error.duplicate': '该邮箱已有待审核的注册',
    'saas.register.error.network': '网络错误，请稍后重试。',
    'saas.register.backHome': '← 返回首页',

    'saas.admin.title': '超管控制台',
    'saas.admin.tab.stores': '店铺管理',
    'saas.admin.tab.signups': '注册审核',
    'saas.admin.allStores': '所有店铺',
    'saas.admin.pendingSignups': '待审核注册',
    'saas.admin.btn.enter': '进入店铺',
    'saas.admin.btn.users': '用户管理',
    'saas.admin.btn.suspend': '暂停',
    'saas.admin.btn.activate': '激活',
    'saas.admin.btn.approve': '批准',
    'saas.admin.btn.reject': '拒绝',
    'saas.admin.btn.delete': '删除',
    'saas.admin.btn.disable': '停用',
    'saas.admin.btn.enable': '启用',
    'saas.admin.users.title': '用户 — {name}',
    'saas.admin.users.colUsername': '用户名',
    'saas.admin.users.colName': '姓名',
    'saas.admin.users.colRole': '角色',
    'saas.admin.users.colStatus': '状态',
    'saas.admin.status.active': '已激活',
    'saas.admin.status.disabled': '已停用',
    'saas.admin.loading': '加载中…',
    'saas.admin.empty.stores': '暂无店铺。',
    'saas.admin.empty.signups': '暂无待审核注册。',
    'saas.admin.empty.users': '该店铺暂无用户。',
    'saas.admin.toast.approved': '店铺 {name} 已批准！',
    'saas.admin.toast.rejected': '注册已拒绝',
    'saas.admin.toast.suspended': '店铺已暂停',
    'saas.admin.toast.activated': '店铺已激活',
    'saas.admin.toast.entered': '已进入 {name}，令牌已更新。',
    'saas.admin.toast.userDeleted': '用户已删除',
    'saas.admin.toast.userDisabled': '用户已停用',
    'saas.admin.toast.userEnabled': '用户已启用',
    'saas.admin.toast.failed': '失败：{error}',
    'saas.admin.toast.networkError': '网络错误',
    'saas.admin.signOut': '退出登录',
    'saas.admin.colActions': '操作',
    'saas.admin.signups.colStore': '店铺',
    'saas.admin.signups.colOwner': '店主',
    'saas.admin.signups.colEmail': '邮箱',
    'saas.admin.signups.colType': '类型',
    'saas.admin.signups.colDate': '日期',
    'saas.admin.status.suspended': '已暂停',
    'saas.admin.status.pending': '待审核',
    'saas.admin.confirm.suspend': '确定暂停此店铺？',
    'saas.admin.confirm.approve': '批准此注册？将自动创建店铺账户。',
    'saas.admin.confirm.reject': '确定拒绝此注册？',
    'saas.admin.confirm.deleteUser': '删除此用户？此操作不可撤销。',
    'saas.admin.confirm.disableUser': '确定停用此用户？',
    'saas.admin.toast.unknownError': '未知错误',
    'saas.admin.toast.approvalFailed': '批准失败',
    'saas.admin.toast.deleteFailed': '删除失败',
    'saas.admin.toast.failedGeneric': '失败',
    'saas.admin.toast.approvedWithUser': '店铺 {name} 已批准！用户名：{username}',
    'saas.admin.btn.edit': '编辑',
    'saas.admin.btn.resetPw': '重置密码',
    'saas.admin.btn.emailPw': '发送密码到邮箱',
    'saas.admin.editUser.title': '编辑用户',
    'saas.admin.editUser.username': '用户名',
    'saas.admin.editUser.displayName': '显示名称',
    'saas.admin.editUser.email': '邮箱',
    'saas.admin.editUser.password': '新密码（留空保持不变）',
    'saas.admin.editUser.cancel': '取消',
    'saas.admin.editUser.save': '保存',
    'saas.admin.editUser.saving': '保存中...',
    'saas.admin.toast.userUpdated': '用户已更新',
    'saas.admin.confirm.resetPw': '确定重置此用户密码？将生成新密码。',
    'saas.admin.confirm.emailPw': '确定重置密码并通过邮箱发送给用户？',
    'saas.admin.toast.passwordReset': '密码已重置',
    'saas.admin.toast.emailPwSent': '密码已成功发送到邮箱',
    'saas.admin.emailPwWarning': '密码已重置但邮件发送失败：\n{warning}',
    'saas.admin.resetPwResult': '用户 {username} 的密码已重置\n新密码：{password}\n\n请安全地分享给用户。',
    'saas.admin.btn.deleteStore': '删除',
    'saas.admin.delete.title': '删除店铺',
    'saas.admin.delete.confirm': '请输入当前都柏林时间 (HHMM) 作为二级密码确认。所有店铺数据和用户将被永久删除。',
    'saas.admin.delete.hint': '当前都柏林时间：',
    'saas.admin.delete.label': '二级密码 (HHMM)',
    'saas.admin.delete.cancel': '取消',
    'saas.admin.delete.confirmBtn': '确认删除',
    'saas.admin.delete.noPw': '请输入密码',
    'saas.admin.delete.finalWarning': '此操作将永久删除店铺及所有关联用户。确定继续？',
    'saas.admin.delete.deleting': '删除中...',
    'saas.admin.toast.storeDeleted': '店铺及所有用户已删除',

    /* ─── SaaS Dashboard Password ─── */
    'saas.dash.password.title': '修改密码',
    'saas.dash.password.current': '当前密码',
    'saas.dash.password.new': '新密码',
    'saas.dash.password.confirm': '确认新密码',
    'saas.dash.password.btn': '更新密码',
    'saas.dash.password.saving': '更新中...',
    'saas.dash.password.saved': '密码更新成功！',
    'saas.dash.password.errorRequired': '请填写所有密码字段',
    'saas.dash.password.errorLength': '新密码至少需要 6 个字符',
    'saas.dash.password.errorMismatch': '两次输入的密码不一致',
    'saas.dash.password.errorGeneric': '密码更新失败',

    /* ─── SaaS Landing ─── */
    'saas.landing.nav.features': '功能特点',
    'saas.landing.nav.pricing': '价格方案',
    'saas.landing.nav.storeLogin': '店主登录',
    'saas.landing.nav.createStore': '创建店铺',
    'saas.landing.hero.title': 'TechCross SaaS 助您轻松管理维修店',
    'saas.landing.hero.subtitle': '维修、收银、库存、员工管理 — 一站式平台，应有尽有。',
    'saas.landing.hero.btnCreate': '创建店铺',
    'saas.landing.hero.btnLogin': '店主登录',
    'saas.landing.features.title': '一站式店铺管理',
    'saas.landing.features.subtitle': '专为手机和电子产品维修店打造，由懂行的人设计。',
    'saas.landing.features.pos': '收银系统',
    'saas.landing.features.posDesc': '快速直观的 POS，支持条码扫描、折扣和多种支付方式。',
    'saas.landing.features.inventory': '库存管理',
    'saas.landing.features.inventoryDesc': '追踪库存、管理供应商、处理采购订单，低库存自动提醒。',
    'saas.landing.features.repair': '维修流程',
    'saas.landing.features.repairDesc': '完整的维修生命周期：登记、诊断、零件订购、状态更新、取机。',
    'saas.landing.features.vat': 'VAT 合规',
    'saas.landing.features.vatDesc': '自动计算 23%/13.5% VAT，二手商品利润增值税方案，税务报告。',
    'saas.landing.features.receipts': '收据与发票',
    'saas.landing.features.receiptsDesc': '专业收据和 VAT 发票，自动编号，支持电邮发送。',
    'saas.landing.features.whatsapp': 'WhatsApp 集成',
    'saas.landing.features.whatsappDesc': '通过 WhatsApp 直接向客户发送维修进度、报价和发票。',
    'saas.landing.features.reports': '数据报表',
    'saas.landing.features.reportsDesc': '日报、利润表、VAT 汇总和月度结算报告。',
    'saas.landing.features.staff': '多员工管理',
    'saas.landing.features.staffDesc': '基于角色的账户：员工、经理、店主，权限精细可控。',
    'saas.landing.features.printing': '热敏打印',
    'saas.landing.features.printingDesc': 'ESC/POS 收据打印，支持本地打印代理，兼容标准 80mm 打印机。',
    'saas.landing.screenshots.title': '功能预览',
    'saas.landing.screenshots.subtitle': '界面简洁、操作流畅、专为柜台场景打造。',
    'saas.landing.pricing.title': '简洁定价',
    'saas.landing.pricing.subtitle': '从小做起，随需扩展。无隐藏费用。',
    'saas.landing.pricing.starter': '入门版',
    'saas.landing.pricing.perMonth': '每月',
    'saas.landing.pricing.starter.f1': '每月 500 笔交易',
    'saas.landing.pricing.starter.f2': '1 个员工账户',
    'saas.landing.pricing.starter.f3': '基础库存管理',
    'saas.landing.pricing.starter.f4': '收据打印',
    'saas.landing.pricing.starter.f5': '邮件支持',
    'saas.landing.pricing.starterBtn': '开始使用',
    'saas.landing.pricing.pro': '专业版',
    'saas.landing.pricing.pro.f1': '无限交易',
    'saas.landing.pricing.pro.f2': '5 个员工账户',
    'saas.landing.pricing.pro.f3': '完整库存 + 供应商管理',
    'saas.landing.pricing.pro.f4': 'VAT 合规与报表',
    'saas.landing.pricing.pro.f5': 'WhatsApp 集成',
    'saas.landing.pricing.pro.f6': '优先支持',
    'saas.landing.pricing.proBtn': '开始使用',
    'saas.landing.pricing.enterprise': '企业版',
    'saas.landing.pricing.enterprise.f1': '无限所有',
    'saas.landing.pricing.enterprise.f2': '无限员工账户',
    'saas.landing.pricing.enterprise.f3': '多店铺支持',
    'saas.landing.pricing.enterprise.f4': '自定义集成',
    'saas.landing.pricing.enterprise.f5': '专属客户经理',
    'saas.landing.pricing.enterprise.f6': '99.9% SLA',
    'saas.landing.pricing.enterpriseBtn': '联系我们',
    'saas.landing.cta.title': '准备好了吗？',
    'saas.landing.cta.subtitle': '加入信赖 TechCross 管理业务的店主行列。',
    'saas.landing.cta.btn': '创建店铺 — 免费开始',
    'saas.landing.footer': '© 2026 TechCross。保留所有权利。',

    'saas.dash.greeting.super': '超管面板',
    'saas.dash.greeting.owner': '店主面板',
    'saas.dash.greeting.staff': '员工面板',
    'saas.dash.welcome': '欢迎！',
    'saas.dash.subtitle': '您已登录 SaaS 平台。',
    'saas.dash.username': '用户名',
    'saas.dash.name': '姓名',
    'saas.dash.role': '角色',
    'saas.dash.storeId': '店铺 ID',
    'saas.dash.storeNone': '无（超管）',
    'saas.dash.adminBanner.title': '欢迎，超级管理员',
    'saas.dash.adminBanner.desc': '您拥有所有店铺的完整访问权限。',
    'saas.dash.adminBanner.btn': '打开管理控制台',
    'saas.dash.signOut': '退出登录',

    /* ─── Store Settings (SaaS) ─── */
    'saas.dash.storeInfo': '店铺信息',
    'saas.dash.settings.title': '店铺设置',
    'saas.dash.settings.logo': '店铺 Logo',
    'saas.dash.settings.uploadLogo': '上传 Logo',
    'saas.dash.settings.logoTooBig': 'Logo 不能超过 2MB',
    'saas.dash.settings.storeName': '店铺名称',
    'saas.dash.settings.storeNamePlaceholder': '您的店铺名称',
    'saas.dash.settings.address': '地址',
    'saas.dash.settings.addressPlaceholder': '完整店铺地址',
    'saas.dash.settings.phone': '电话',
    'saas.dash.settings.phonePlaceholder': '电话号码',
    'saas.dash.settings.email': '邮箱',
    'saas.dash.settings.emailPlaceholder': '邮箱地址',
    'saas.dash.settings.vatNumber': 'VAT 号码',
    'saas.dash.settings.vatPlaceholder': 'IE1234567X',
    'saas.dash.settings.receiptTC': '小票条款与条件',
    'saas.dash.settings.tcPlaceholder': '例如：14天后不退款，保修条款...',
    'saas.dash.settings.save': '保存设置',
    'saas.dash.settings.saving': '保存中...',
    'saas.dash.settings.saved': '设置已保存！',
    'saas.dash.settings.reset': '重置',
  },
};

// ─── Current language (stored in localStorage) ───
function getLang() {
  return localStorage.getItem('inv_lang') || 'en';
}

function setLang(lang) {
  localStorage.setItem('inv_lang', lang);
}

// ─── Translate a key with optional variables ───
function __(key, vars) {
  const lang = getLang();
  let text = LANG[lang]?.[key] || LANG['en']?.[key] || key;
  if (vars && typeof vars === 'object') {
    for (const [k, v] of Object.entries(vars)) {
      text = text.replace('{' + k + '}', v);
    }
  }
  return text;
}

// ─── Apply translations to all data-i18n elements ───
function applyLang() {
  const lang = getLang();
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    let text = LANG[lang]?.[key] || LANG['en']?.[key] || key;
    // Check for data-i18n-vars
    const varsAttr = el.getAttribute('data-i18n-vars');
    if (varsAttr) {
      try {
        const vars = JSON.parse(varsAttr);
        for (const [k, v] of Object.entries(vars)) {
          text = text.replace('{' + k + '}', v);
        }
      } catch(e) {}
    }
    el.textContent = text;
  });

  // Update placeholders
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    el.placeholder = LANG[lang]?.[key] || LANG['en']?.[key] || key;
  });

  // Update language toggle button text
  const toggle = document.getElementById('langToggle');
  if (toggle) {
    toggle.textContent = lang === 'en' ? '中' : 'EN';
  }
}

// ─── Toggle language ───
function toggleLang() {
  const current = getLang();
  const next = current === 'en' ? 'zh' : 'en';
  setLang(next);
  applyLang();
}
