/**
 * MonthlyReport Model — Stored monthly tax report
 *
 * SYSTEM_SPEC §12 — MONTHLY REPORT
 * Once generated, the monthly report is IMMUTABLE and becomes the
 * sole tax record for that month. All underlying Transactions can
 * be safely deleted after generation.
 *
 * Data source: DailyClose snapshots for the month.
 * Generated by: ROOT on demand.
 */

const mongoose = require('mongoose');

const DailySummarySchema = new mongoose.Schema({
  date:          { type: String, required: true }, // YYYY-MM-DD
  grossSales:    { type: Number, default: 0 },
  refundTotal:   { type: Number, default: 0 },
  netSales:      { type: Number, default: 0 },
  cashTotal:     { type: Number, default: 0 },
  cardTotal:     { type: Number, default: 0 },
  standard23Sales:  { type: Number, default: 0 },
  standard23Vat:    { type: Number, default: 0 },
  reduced135Sales:  { type: Number, default: 0 },
  reduced135Vat:    { type: Number, default: 0 },
  marginSales:      { type: Number, default: 0 },
  marginVat:        { type: Number, default: 0 },
  expenseTotal:     { type: Number, default: 0 },
  expenseCash:      { type: Number, default: 0 },
  expenseCard:      { type: Number, default: 0 },
  netCash:          { type: Number, default: 0 },
}, { _id: false });

const MonthlyReportSchema = new mongoose.Schema({
  month:        { type: String, required: true, unique: true, trim: true }, // YYYY-MM
  status:       { type: String, enum: ['generated'], default: 'generated' },
  generatedAt:  { type: Date, default: Date.now, immutable: true },
  generatedBy:  { type: mongoose.Schema.Types.ObjectId, ref: 'InvUser', required: true },

  // Daily breakdown — aggregated from DailyClose snapshots
  dailyData: [DailySummarySchema],

  // Monthly totals
  summary: {
    totalDays:          { type: Number, default: 0 },
    grossSales:         { type: Number, default: 0 },
    refundTotal:        { type: Number, default: 0 },
    netSales:           { type: Number, default: 0 },
    cashTotal:          { type: Number, default: 0 },
    cardTotal:          { type: Number, default: 0 },
    totalSales:         { type: Number, default: 0 },
    standard23VatTotal: { type: Number, default: 0 },
    reduced135VatTotal: { type: Number, default: 0 },
    marginVatTotal:     { type: Number, default: 0 },
    totalVatPayable:    { type: Number, default: 0 },
    expenseTotal:       { type: Number, default: 0 },
    expenseCash:        { type: Number, default: 0 },
    expenseCard:        { type: Number, default: 0 },
    netCash:            { type: Number, default: 0 },
  },

  // Coverage — how many transactions, receipt range
  transactionCount: { type: Number, default: 0 },
  receiptRange: {
    from: { type: String },
    to:   { type: String },
  },

  // Margin items detail for audit
  marginItems: [{
    receiptNumber: String,
    name:   String,
    sku:    String,
    margin: Number,
    vatPayable: Number,
  }],
}, { timestamps: true });

// ─── Immutability guard ────────────────────────────────────────────
// Monthly report is immutable once generated.
MonthlyReportSchema.pre('save', function () {
  if (!this.isNew) {
    throw new Error('MONTHLY_REPORT_IMMUTABLE: Monthly report cannot be modified after generation.');
  }
});

MonthlyReportSchema.pre('findOneAndUpdate', function () {
  throw new Error('Monthly report cannot be updated');
});

MonthlyReportSchema.pre('findOneAndDelete', function () {
  throw new Error('Monthly report cannot be deleted');
});

MonthlyReportSchema.pre('deleteOne', function () {
  throw new Error('Monthly report cannot be deleted');
});

module.exports = mongoose.model('MonthlyReport', MonthlyReportSchema);
